name: Build projects
on:
    pull_request:
    push:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v23

      - name: Override nix-daemon build directory
        run: |
          sudo mkdir -p /nix/tmp
          sudo chmod ug=rwx,o=rwxt /nix/tmp

          sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
          sudo tee /etc/systemd/system/nix-daemon.service.d/override.conf >/dev/null <<EOF
          [Service]
          Environment=TMPDIR=/nix/tmp
          EOF

          sudo systemctl daemon-reload
          sudo systemctl restart nix-daemon

      - name: Setup automatic caching
        uses: DeterminateSystems/magic-nix-cache-action@v15

      - name: Build known packages
        run: |
          for i in dewclaw-env dewclaw-book; do
            nix build ".#$i"
            mkdir -p "out/$i"
            output=$(readlink -f result)
            cp -vr --dereference "$output/." "out/$i"
          done

      - name: Upload archive to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: 'out'
          path: 'out'
          if-no-files-found: error
